services:
  dst_caves:
    build: .
    container_name: dst_caves
    ports:
      - 10998:10998/udp
    networks:
      - dst_cluster
    links:
      - dst_master
    volumes:
      - ./DSTClusterConfig:/root/.klei/DoNotStarveTogether/DSTWhalesCluster
      - ./volumes/mods:/root/server_dst/mods
    environment:
      - SHARD_NAME=Caves
    # command: ["tail", "-f", "/dev/null"]

  dst_master:
    build: .
    container_name: dst_master
    networks:
      - dst_cluster
    ports:
      - 10999:10999/udp
    volumes:
      - ./DSTClusterConfig:/root/.klei/DoNotStarveTogether/DSTWhalesCluster
      - ./volumes/mods:/root/server_dst/mods
    environment:
      - SHARD_NAME=Master
    # command: ["tail", "-f", "/dev/null"]

    # These allow to stdin when attaching to the container via `docker attach`
    # Any server commands should be sent to the master shard as it manages its slaves (Caves)
    stdin_open: true
    tty: true

networks:
  dst_cluster:
